### ISSUE TITLE
Failed to precompile flutter_launcher_icons:main:

### ISSUE THREAD

**Issue by MalcolmMielle** [fluttercommunity/flutter_launcher_icons#74]
Hello !

Iäve setup my config file as in [here](https://pub.dartlang.org/packages/flutter_launcher_icons) and then, after getting the package, I run `flutter packages pub run flutter_launcher_icons:main`

Sadly here is the output:

```
Failed to precompile flutter_launcher_icons:main:
file:///home/malcolm/external_sources/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.0.5/lib/src/bitmap_font.dart:303:40: Error: Too many positional arguments: 1 allowed, but 3 found.
Try removing the extra positional arguments.
          var info = new XML.XmlElement(new XML.XmlName('info'), attrs, []);
                                       ^
file:///home/malcolm/external_sources/flutter/.pub-cache/hosted/pub.dartlang.org/xml-3.2.4/lib/xml/nodes/element.dart:17:3: Context: Found this candidate, but the arguments don't match.
  XmlElement(this.name,
  ^
file:///home/malcolm/external_sources/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.0.5/lib/src/bitmap_font.dart:308:40: Error: Too many positional arguments: 1 allowed, but 3 found.
Try removing the extra positional arguments.
          var node = new XML.XmlElement(new XML.XmlName('common'), attrs, []);
                                       ^
file:///home/malcolm/external_sources/flutter/.pub-cache/hosted/pub.dartlang.org/xml-3.2.4/lib/xml/nodes/element.dart:17:3: Context: Found this candidate, but the arguments don't match.
  XmlElement(this.name,
  ^
file:///home/malcolm/external_sources/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.0.5/lib/src/bitmap_font.dart:313:40: Error: Too many positional arguments: 1 allowed, but 3 found.
Try removing the extra positional arguments.
          var page = new XML.XmlElement(new XML.XmlName('page'), attrs, []);
                                       ^
file:///home/malcolm/external_sources/flutter/.pub-cache/hosted/pub.dartlang.org/xml-3.2.4/lib/xml/nodes/element.dart:17:3: Context: Found this candidate, but the arguments don't match.
  XmlElement(this.name,
  ^
file:///home/malcolm/external_sources/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.0.5/lib/src/bitmap_font.dart:321:40: Error: Too many positional arguments: 1 allowed, but 3 found.
Try removing the extra positional arguments.
          var node = new XML.XmlElement(new XML.XmlName('char'), attrs, []);
                                       ^
file:///home/malcolm/external_sources/flutter/.pub-cache/hosted/pub.dartlang.org/xml-3.2.4/lib/xml/nodes/element.dart:17:3: Context: Found this candidate, but the arguments don't match.
  XmlElement(this.name,
  ^
file:///home/malcolm/external_sources/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.0.5/lib/src/bitmap_font.dart:329:40: Error: Too many positional arguments: 1 allowed, but 3 found.
Try removing the extra positional arguments.
          var node = new XML.XmlElement(new XML.XmlName('kerning'), attrs, []);
                                       ^
file:///home/malcolm/external_sources/flutter/.pub-cache/hosted/pub.dartlang.org/xml-3.2.4/lib/xml/nodes/element.dart:17:3: Context: Found this candidate, but the arguments don't match.
  XmlElement(this.name,
  ^
pub finished with exit code 1
```

Here is my config file
```

name: appname
description: Someapp

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Your other dev_dependencies here
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  path_provider: ^0.4.1
  intl: ^0.15.7
  flutter_local_notifications:
  scheduled_notifications: ^1.0.0
  http: ^0.12.0
  url_launcher:
  flutter_launcher_icons: ^0.7.0



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/avater.jpg"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
      - images/avatar.jpg
      - images/flutter.png
      - assets/userdata.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

```

**Comment by lcrocker** [comment]
I'm getting exactly the same...looks like an incompatible XML package, I'll investigate.

**Comment by lcrocker** [comment]
Looks like an API change. The "attributes" and "children" arguments to the XmlElement constructor are no longer positional, but optional named arguments.

**Comment by finzaiko** [comment]
Yes, I have same issue

**Comment by RameesFazal** [comment]
> > I'm getting exactly the same...looks like an incompatible XML package.
> > Apparently, at some point the API for the xml packaged changed: the XmlElement constructor no longer takes "attributes" and "children" as positional arguments, but only as named arguments.
> > There are 9 invocations of that constructor in bitmap_font.dart. Adding "attributes:" and "children:" to the second and third arguments of each call allows it to compile successfully.
> 
> can u give me some example please?

Hi fachirzalrifadhi
You need to go to the file location mentioned in error(in this case file:///home/malcolm/external_sources/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.0.5/lib/src/bitmap_font.dart) and remove the last two arguments from xml constructor
To be more clear if the constuctor is like below
var node = new XML.XmlElement(new XML.XmlName('char'), attrs, []);
It will become
var node = new XML.XmlElement(new XML.XmlName('char'));
You need to do this process for all the lines which in error list which u got. Then execute the command it will work.

**Comment by turbobh** [comment]
I have the same issue. I fixed this by remove all the arguments except the first one.
Steps:
- Open **bitmap_font.dart** file with any TextEditor
- Find all the "**new XML.XmlElement(**" line then remove all the arguments except the first one
- Save the file
- Restart your IDE

**Comment by fachrizalrifahdi** [comment]
> I have the same issue. I fixed this by remove all the arguments except the first one.
> Steps:
> 
> * Open **bitmap_font.dart** file with any TextEditor
> * Find all the "**new XML.XmlElement(**" line then remove all the arguments except the first one
> * Save the file
> * Restart your IDE

can u give me the example please?

**Comment by fachrizalrifahdi** [comment]
> > > I'm getting exactly the same...looks like an incompatible XML package.
> > > Apparently, at some point the API for the xml packaged changed: the XmlElement constructor no longer takes "attributes" and "children" as positional arguments, but only as named arguments.
> > > There are 9 invocations of that constructor in bitmap_font.dart. Adding "attributes:" and "children:" to the second and third arguments of each call allows it to compile successfully.
> > 
> > 
> > can u give me some example please?
> 
> Hi fachirzalrifadhi
> You need to go to the file location mentioned in error(in this case file:///home/malcolm/external_sources/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.0.5/lib/src/bitmap_font.dart) and remove the last two arguments from xml constructor
> To be more clear if the constuctor is like below
> var node = new XML.XmlElement(new XML.XmlName('char'), attrs, []);
> It will become
> var node = new XML.XmlElement(new XML.XmlName('char'));
> You need to do this process for all the lines which in error list which u got. Then execute the command it will work.

isn't still work

**Comment by RameesFazal** [comment]
> > > > I'm getting exactly the same...looks like an incompatible XML package.
> > > > Apparently, at some point the API for the xml packaged changed: the XmlElement constructor no longer takes "attributes" and "children" as positional arguments, but only as named arguments.
> > > > There are 9 invocations of that constructor in bitmap_font.dart. Adding "attributes:" and "children:" to the second and third arguments of each call allows it to compile successfully.
> > > 
> > > 
> > > can u give me some example please?
> > 
> > 
> > Hi fachirzalrifadhi
> > You need to go to the file location mentioned in error(in this case file:///home/malcolm/external_sources/flutter/.pub-cache/hosted/pub.dartlang.org/image-2.0.5/lib/src/bitmap_font.dart) and remove the last two arguments from xml constructor
> > To be more clear if the constuctor is like below
> > var node = new XML.XmlElement(new XML.XmlName('char'), attrs, []);
> > It will become
> > var node = new XML.XmlElement(new XML.XmlName('char'));
> > You need to do this process for all the lines which in error list which u got. Then execute the command it will work.
> 
> isn't still work

had same issue for me. IT worked. Have you replaced it in all lines mentioned in your error log? If still not working post the error which you are getting.

**Comment by fachrizalrifahdi** [comment]
fixed i've tried delete some args to be like this on bitmap_font.dart

`  XML.XmlDocument _parseTextFnt(String content) {
    var children = <XML.XmlNode>[];
    var pageList = <XML.XmlNode>[];
    var charList = <XML.XmlNode>[];
    var kerningList = <XML.XmlNode>[];
    var charsAttrs;
    var kerningsAttrs;

    List<String> lines = content.split('\n');

    for (String line in lines) {
      if (line.isEmpty) {
        continue;
      }

      List<String> tk = line.split(' ');
      switch (tk[0]) {
        case 'info':
          var attrs = _parseParameters(tk);
          var info = new XML.XmlElement(new XML.XmlName('info'));
          children.add(info);
          break;
        case 'common':
          var attrs = _parseParameters(tk);
          var node = new XML.XmlElement(new XML.XmlName('common'));
          children.add(node);
          break;
        case 'page':
          var attrs = _parseParameters(tk);
          var page = new XML.XmlElement(new XML.XmlName('page'));
          pageList.add(page);
          break;
        case 'chars':
          charsAttrs = _parseParameters(tk);
          break;
        case 'char':
          var attrs = _parseParameters(tk);
          var node = new XML.XmlElement(new XML.XmlName('char'));
          charList.add(node);
          break;
        case 'kernings':
          kerningsAttrs = _parseParameters(tk);
          break;
        case 'kerning':
          var attrs = _parseParameters(tk);
          var node = new XML.XmlElement(new XML.XmlName('kerning'));
          kerningList.add(node);
          break;
      }
    }

    if (charsAttrs != null || charList.isNotEmpty) {
      var node = new XML.XmlElement(new XML.XmlName('chars'));
      children.add(node);
    }

    if (kerningsAttrs != null || kerningList.isNotEmpty) {
      var node = new XML.XmlElement(new XML.XmlName('kernings'));
      children.add(node);
    }

    if (pageList.isNotEmpty) {
      var pages = new XML.XmlElement(new XML.XmlName('pages'));
      children.add(pages);
    }

    var xml = new XML.XmlElement(new XML.XmlName('font'));
    var doc = new XML.XmlDocument([xml]);

    return doc;
  }`

**Comment by safeforge** [comment]
seems to be related to brendan-duncan/image#89

**Comment by fayaz07** [comment]
even I faced the same issue

**Comment by MarkOSullivan94** [comment]
Currently away atm but will be back this weekend and I'll try and investigate this issue then

**Comment by matthewhuie** [comment]
This has been patched in the master branch of `brendan-duncan/image`.

You could temporarily point your `flutter_launcher_icons` package to Github to get the latest patch.

```yaml
# ~/.pub-cache/hosted/pub.dartlang.org/flutter_launcher_icons-0.7.0/pubspec.yaml

image:
  git:
    url: https://github.com/brendan-duncan/image.git
```

**Comment by MarkOSullivan94** [comment]
I think this should be working fine now. Looks like the [xml package](https://github.com/renggli/dart-xml) developer published an update which caused a ripple effect causing some issues with packages which depended on it.

I tried switching the image dependency to the commit which merged the PR for the fix in the image package but that no longer seems to be working, so whenever I removed my changes and tested the package, it worked fine for me.

Let me know if anyone is still having issues otherwise I'll close this issue.
